# Generated by Django 6.0.3 on 2026-03-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('NAO_RESPONDIDA', 'Não Respondida'), ('RESPONDIDA', 'Respondida')], default='NAO_RESPONDIDA', max_length=20)),
                ('data_reclamacao', models.DateTimeField(auto_now_add=True)),
                ('urgencia', models.CharField(choices=[('NAO_URGENTE', 'Não Urgente'), ('URGENTE', 'Urgente')], default='NAO_URGENTE', max_length=20)),
            ],
        ),
    ]
